### ISSUE TITLE
Seg fault when interface is missing link-local address

### ISSUE THREAD

**Issue by Austinpayne** [troglobit/pim6sd#29]
I'm running into a seg fault on a Raspberry Pi4 when one configured interface is missing a link-local address. It appears to be because the `age_vif` timer is trying to send out a hello on the interface and then crashing because of bad memory where the address should be.

I've fixed it [in a separate branch](https://github.com/Austinpayne/pim6sd/commit/24bc5bd6fdefd0bb8f9dbf0ba7c4f940edcf8caa) but I'm not entirely sure if this is right fix (seems like maybe this VIF shouldn't even be getting this far?). If it is, I'm happy to open a PR just let me know.

**Host info**
```
pi@r0:pim6sd [fix/eth-no-ipv6-lla] $ uname -a
Linux r0.local 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
pi@r0:pim6sd [fix/eth-no-ipv6-lla] $ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**GDB output**
```
pi@r0:pim6sd [fix/eth-no-ipv6-lla] $ cat pim6sd.conf
default_phyint_status disable;
phyint eth0 enable;
phyint eth1 enable;
pi@r0:build [fix/eth-no-ipv6-lla] $ sudo gdb --args ./src/pim6sd -f ../pim6sd.conf -n -d all
GNU gdb (Debian 8.2.1-2+b3) 8.2.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./src/pim6sd...done.
(gdb) r
Starting program: /home/pi/pim6sd/build/src/pim6sd -f ../pim6sd.conf -n -d all
debug level 0xffffffffffffffff: mld_proto, mld_timer, mld_member, mld, switch, trace, mtrace, traceroute, timeout, callout, pkt, packets, interfaces, vif, kernel, cache, mfc, k_cache, k_mfc, rsrr, pim_detail, pim_hello, pim_neighbors, pim_register, registers, pim_join_prune, pim_j_p, pim_jp, pim_bootstrap, pim_bsr, bsr, bootstrap, pim_asserts, pim_cand_rp, pim_c_rp, pim_rp, rp, pim_routes, pim_routing, pim_mrt, pim_timers, pim_rpf, rpf, pim, routes, routing, mrt, routers, mrouters, neighbors, timers, asserts, all, 3
18:21:55.315 pim6sd version 2.1.0-beta1 starting
18:21:55.315 65536 octets allocated for the emit/recept buffer mld6
18:21:55.315 Buffer reception size for socket 4 : 262144 in 0 iterations
18:21:55.315 65536 octets allocated for the emit/recept buffer pim6
18:21:55.315 Buffer reception size for socket 5 : 262144 in 0 iterations
18:21:55.315 Interfaces world initialized...
18:21:55.315 Getting vifs from ../pim6sd.conf
<3>default_phyint_status
<3>disable
<3>end cnf [;] (1)
<3>begin phyint [phyint] (6)
<7>eth0
<9>enable
<9>end phyint [;] (1)
<3>begin phyint [phyint] (6)
<7>eth1
<9>enable
<9>end phyint [;] (1)
parse successed.
18:21:55.316 pim_hello_period set to: 30
18:21:55.316 pim_hello_holdtime set to: 105
18:21:55.316 pim_join_prune_period set to: 60
18:21:55.316 pim_join_prune_holdtime set to: 210
18:21:55.316 timer interval set to: 5
18:21:55.316 PIM data timeout set to: 210
18:21:55.316 PIM register suppression timeout set to: 60
18:21:55.316 PIM register probe time set to: 5
18:21:55.316 PIM assert timeout set to: 180
18:21:55.316 reg_rate_limit set to 100000 (bits/s)
18:21:55.316 reg_rate_interval set to  20 s.
18:21:55.316 data_rate_limit set to 100000 (bits/s)
18:21:55.316 data_rate_interval set to 20 s.
18:21:55.316 Getting vifs from kernel
18:21:55.316 warning - Not registering detected interface lo: Operation not permitted
18:21:55.316 warning - Not registering detected interface lo: Operation not permitted
18:21:55.316 Installing eth0 (fd42:de00:c832:9fc:1b3e:bf07:72ee:d0c8 on subnet ::/64) ,as vif #2 - rate = 0
18:21:55.317 Installing eth0 (fe80::1f0:10f3:e995:5829 on subnet ::/64) ,as vif #2 - rate = 0
18:21:55.317 PIM kernel initialization done
18:21:55.317 Interface register_mif0 (subnet ::/0), installed on vif #2 - rate = 0
18:21:55.317 eth0 comes up ,vif #0 now in service
18:21:55.317 SENT Multicast Listener Query     from fe80::1f0:10f3:e995:5829 to ff02::1
18:21:55.317 eth1 is DOWN; vif #1 out of service
18:21:55.317 register vifi : 2 , register pifi : 2
18:21:55.318 register_mif0 comes up ,vif #2 now in service
18:21:55.318 Local Cand-RP address is : fd42:de00:c832:9fc:1b3e:bf07:72ee:d0c8
18:21:55.318 Local Cand-RP priority is : 0
18:21:55.319 Local Cand-RP advertisement period is : 0 sec.
18:21:55.319 no group_prefix was specified
18:21:55.319 Local BSR address: fd42:de00:c832:9fc:1b3e:bf07:72ee:d0c8
18:21:55.319 Local BSR priority : 0
18:21:55.319 Local BSR period is : 0 sec.
18:21:55.319 Local BSR hash mask length: 0

Multicast Interface Table
 Mif   PhyIF Local-Address/Prefixlen                     Scope GenID    Flags
  0     eth0 fe80::1f0:10f3:e995:5829/64                 2     729ed2e  QRY NO-NBR DR
             fd42:de00:c832:9fc:1b3e:bf07:72ee:d0c8/64   0
             Timers: PIM hello = 0:30, MLD query = 0:30
             possible MLD version = 1
             Timers: PIM hello = 0:00, MLD query = 0:00
             possible MLD version = 1
  2   regist fe80::1f0:10f3:e995:5829/64                 2     0        REGISTER
             Timers: PIM hello = 0:00, MLD query = 0:00
             possible MLD version = 1

Multicast Routing Table
 Source          Group           RP-addr         Flags
--------------------------(*,*,RP)--------------------------
Number of Groups: 0
Number of Cache MIRRORs: 0

18:21:55.319 Receiving PIM v2 Hello              from fe80::1f0:10f3:e995:5829
18:21:56.681 accept_listener_report: group(ff02::1:ffee:d0c8) has the link-local scope. discard
18:22:00.233 accept_listener_report: group(ff02::d) has the link-local scope. discard
18:22:01.234 eth1 comes up ,vif #1 now in service
18:22:01.234 warning - Interface eth1 has no link-local address, cannot send MLD query.

Multicast Interface Table
 Mif   PhyIF Local-Address/Prefixlen                     Scope GenID    Flags
  0     eth0 fe80::1f0:10f3:e995:5829/64                 2     729ed2e  QRY NO-NBR DR
             fd42:de00:c832:9fc:1b3e:bf07:72ee:d0c8/64   0
             Timers: PIM hello = 0:25, MLD query = 0:25
             possible MLD version = 1
             Timers: PIM hello = 0:04, MLD query = 2:05
             possible MLD version = 1
  2   regist fe80::1f0:10f3:e995:5829/64                 2     0        REGISTER
             Timers: PIM hello = 0:00, MLD query = 0:00
             possible MLD version = 1

Multicast Routing Table
 Source          Group           RP-addr         Flags
--------------------------(*,*,RP)--------------------------
Number of Groups: 0
Number of Cache MIRRORs: 0

---------------------------RP-Set----------------------------
Current BSR address: :: Prio: 0 Timeout: 155
RP-address(Upstream)/Group prefix             Prio Hold Age

18:22:01.245 RECV UNKNOWN ICMPv6 message: type = 0x8f, code = 0x00  from a non link local address: ::
18:22:01.385 RECV UNKNOWN ICMPv6 message: type = 0x8f, code = 0x00  from a non link local address: ::
18:22:01.513 accept_listener_report: group(ff02::1:ff00:0) has the link-local scope. discard
18:22:03.305 accept_listener_report: group(ff02::fb) has the link-local scope. discard
18:22:03.561 accept_listener_report: group(ff02::2) has the link-local scope. discard
18:22:03.821 accepting multicast listener report: src fe80::1f0:10f3:e995:5829,dst ff05::2, grp ff05::2
18:22:03.822 The group doesn't exist, trying to add it
18:22:03.822 create group entry, group ff05::2
18:22:05.097 accept_listener_report: group(ff02::1:ff95:5829) has the link-local scope. discard

Program received signal SIGSEGV, Segmentation fault.
0x000000555556900c in pim6_cksum (len=<optimized out>, dst=0x5555598b60 <allpim6routers_group+8>, src=0x10, addr=0x55555cf390) at ../../src/pim6.c:505
505	    u_int16_t answer = 0;
(gdb) bt
#0  0x000000555556900c in pim6_cksum (len=<optimized out>, dst=0x5555598b60 <allpim6routers_group+8>, src=0x10, addr=0x55555cf390) at ../../src/pim6.c:505
#1  send_pim6 (buf=0x55555cf390 " ", src=0x8, dst=0x5555598b58 <allpim6routers_group>, type=type@entry=0, datalen=datalen@entry=22) at ../../src/pim6.c:426
#2  0x0000005555569ddc in send_pim6_hello (v=v@entry=0x5555599048 <uvifs+448>, holdtime=<optimized out>) at ../../src/pim6_proto.c:827
#3  0x000000555557362c in age_vifs () at ../../src/timer.c:297
#4  0x0000005555561dc4 in timer (i=<optimized out>) at ../../src/main.c:464
#5  0x0000005555558720 in age_callout_queue (elapsed_time=<optimized out>) at ../../src/callout.c:129
#6  0x00000055555581e8 in timeout (n=-1) at ../../src/main.c:539
#7  main (argc=<optimized out>, argv=<optimized out>) at ../../src/main.c:408
```

**Comment by troglobit** [comment]
Hi, the code is in a state of restoration and much is up in the air.  We're a few who help out from time to time to fix and test, no official release yet.  Your fix looks more than OK, so please do a PR :)

**Comment by Austinpayne** [comment]
Very cool. Thank you for resurrecting the project!
